### ISSUE TITLE
README with outdated link

### ISSUE THREAD

**Issue by paulo-ferraz-oliveira** [aws-cloudformation/awesome-cloudformation#31]
I've not tested other links...

`http://ww38.cfnchecklist.com/` is outdated in the README.

**Comment by paulo-ferraz-oliveira** [comment]
Yeah, I guess the list is not "as" curated, these days. It's a pity...

**Comment by mrinaudo-aws** [comment]
Thank you, @paulo-ferraz-oliveira - it seems the website: `https://cfnchecklist.com/` is no longer available.  Today I tried to  open it as well, and I was redirected to `http://ww38.cfnchecklist.com/`, that is the link you mentioned.

I will now look into expunging this entry from the list.

**Comment by paulo-ferraz-oliveira** [comment]
Hey, @mrinaudo-aws, thanks for looking at this. There seems to be other links that are broken in the README.

**Comment by mrinaudo-aws** [comment]
Hi @paulo-ferraz-oliveira - thank you for your time!  I did go through opening links earlier today, and in the event I had missed a broken link(s) please feel free to open another issue.  Thank you again!

**Comment by mrinaudo-aws** [comment]
@paulo-ferraz-oliveira I have merged the change, and closed this related issue.  Thank you again!
