### ISSUE TITLE
Macro section

### ISSUE THREAD

**Issue by rafalwrzeszcz** [aws-cloudformation/awesome-cloudformation#34]
Hi awsesome-cloudformation team!

I'm the creator of https://github.com/rafalwrzeszcz-wrzasqpl/pl.wrzasq.cform - set of my custom CloudFormation goodies. I wanted to add a link to it in the list but noticed there is no section for macros.

Is this intentional, or just can be added together with first entry?

**Comment by mrinaudo-aws** [comment]
Hi @rafalwrzeszcz - feel free to cut us a PR with your proposed additions for review.
